feat: DevOps agent built with packer
pagopa/terraform-azurerm-v3 pull request #126
Opened 2023-05-24 15:53 UTC by mamari90

### List of changes

- updated azdoa agent to accept custom images
- created new module to build, using packer, custom images (executed manually)

### Motivation and context

the devops agents keep failing, missing some required installed programs. So we decided to create a custom image containing all the required programs, to avoid installing them every time an agent is created

### Type of changes

- [x] Add new module
- [x] Update existing module
- [ ] Remove existing module

### Does this introduce a breaking change?

- [x] Yes
- [ ] No

### Other information

### Run checks

Useful commands to run checks on local machine

```sh
bash .utils/terraform_run_all.sh init local
pre-commit run -a
```

2023-05-24 20:35 UTC, diegolagospagopa commented on azure_devops_agent/README.md
> +```hcl
hcl don't exist,please use ts

2023-05-24 20:39 UTC, diegolagospagopa commented on azure_devops_agent/main.tf
this extension is still needed?

2023-05-24 20:49 UTC, diegolagospagopa commented on azure_devops_agent/main.tf
> +    for_each = var.image_reference != null ? [1] : []
can go in conflict?

2023-05-24 20:52 UTC, diegolagospagopa commented on azure_devops_agent_custom_image/README.md
> +```hcl
```suggestion
```hcl
```ts

2023-05-24 20:54 UTC, diegolagospagopa commented on azure_devops_agent_custom_image/devops_agent.json
> +}
Is this file still valid?

2023-05-24 20:58 UTC, diegolagospagopa commented on azure_devops_agent_custom_image/outputs.tf
> +  description = "Id of the created image"
```suggestion
  description = "Azure id of the custom image you just created"
```

2023-05-24 20:59 UTC, diegolagospagopa requested changes
great job

2023-05-25 08:17 UTC, mamari90 commented on azure_devops_agent/README.md
> +```hcl
it is handled by github

2023-05-25 08:17 UTC, mamari90 commented on azure_devops_agent/main.tf
nope, removed

2023-05-25 08:17 UTC, mamari90 commented on azure_devops_agent/main.tf
> +    for_each = var.image_reference != null ? [1] : []
added a third variable to handle mutual exclusion

2023-05-25 08:19 UTC, mamari90 commented on azure_devops_agent_custom_image/README.md
> +```hcl
hcl is working fine

2023-05-25 08:19 UTC, mamari90 commented on azure_devops_agent_custom_image/devops_agent.json
> +}
removed

2023-05-25 09:19 UTC, merged