Feat: added velero installation and backup module
pagopa/terraform-azurerm-v3 pull request #154
Opened 2023-08-30 09:54 UTC by mamari90

### List of changes

### Motivation and context

### Type of changes

- [x] Add new module
- [x] Update existing module
- [ ] Remove existing module

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

### Other information

### Run checks

Useful commands to run checks on local machine

```sh
bash .utils/terraform_run_all.sh init local
pre-commit run -a
```

2023-08-30 16:05 UTC, mamari90 commented on kubernetes_cluster_velero/01_main.tf
> +  display_name = "velero-application"
done

2023-08-30 16:05 UTC, mamari90 commented on kubernetes_cluster_velero/01_main.tf
> +    velero install --provider azure --plugins velero/velero-plugin-for-microsoft-azure:v1.5.0 \
done

2023-08-30 16:23 UTC, mamari90 commented on kubernetes_cluster_velero/01_main.tf
> +    EOT
not necessary, velero outputs this:
Schedule "prova" created successfully.

2023-08-30 16:23 UTC, mamari90 commented on kubernetes_velero_backup/01_main.tf
> +    EOT
not necessary, velero outputs this:
Schedule "prova" created successfully.

2023-09-07 12:32 UTC, diegolagospagopa requested changes

2023-09-07 12:32 UTC, diegolagospagopa commented on kubernetes_cluster_velero/01_main.tf
> +  account_replication_type        = "LRS"
please allow to choose either ZRS

2023-09-08 09:00 UTC, mamari90 commented on kubernetes_cluster_velero/01_main.tf
> +  account_replication_type        = "LRS"
done

2023-09-08 15:44 UTC, diegolagospagopa approved these changes

2023-09-08 16:01 UTC, merged