feat: User Managed Identity federated within GitHub for CI/CD module
pagopa/terraform-azurerm-v3 pull request #165
Opened 2023-10-03 13:10 UTC by Krusty93

### List of changes

Add a module to make easier and reusable the creation of a user managed identity federated with GitHub.

### Motivation and context

This change adds a new module that can be used by repositories that need to run GitHub Actions and logging in Azure using a password-less approach. Since potentially every repository might need to run Actions against in Azure, I think that creating a new module is worthing because it can help developers maximising code reusability.

The module allows the consumer to set either `ci` or `cd` as `identity_role` value: depending on which one is used, the module updates subscription IAM permissions with a set of Azure built-in roles.

The consumer can also limit the scope of the identity over a single repository environment or branch or even tags.

Module forces the consumer to use a consistent naming style.

### Type of changes

- [X] Add new module
- [ ] Update existing module
- [ ] Remove existing module

### Does this introduce a breaking change?

- [ ] Yes
- [X] No

### Other information

### Run checks

Useful commands to run checks on local machine

```sh
bash .utils/terraform_run_all.sh init local
pre-commit run -a
```

2023-10-03 15:27 UTC, Krusty93 commented on identity_github_runner/outputs.tf
> +output "user_managed_identity" {
Split variables

2023-10-03 15:27 UTC, Krusty93 commented on identity_github_runner/outputs.tf
> +    object_id           = azurerm_user_assigned_identity.identity.principal_id
change name

2023-10-03 15:27 UTC, Krusty93 commented on identity_github_runner/variables.tf
> +variable "project" {
something more explicit

2023-10-03 15:33 UTC, gunzip commented on identity_github_runner/tests/resources.tf
> +resource "azurerm_resource_group" "rg" {
i'd add comments, for every file in this directory, about which lines should (must?) be changed and the rest od the HCL code that should (must?) be kept as is.

2023-10-03 15:40 UTC, diegolagospagopa requested changes

2023-10-03 15:40 UTC, diegolagospagopa commented on identity_github_runner/variables.tf
> +  default     = "identity-rg"
please remove the default because is not standard as name, is better to have as input

2023-10-04 12:47 UTC, Krusty93 commented on identity_github_runner/variables.tf
> +variable "project" {
@diegolagospagopa any suggestion? I have already added the `description` field with `Project name according to PagoPA conventions`, but I don't know if any exists or everyone is aware of it, really

2023-10-04 13:01 UTC, Krusty93 commented on identity_github_runner/tests/main.tf
> +}
I copied this approach from other modules, they're all done in this way

2023-10-04 13:05 UTC, Krusty93 commented on identity_github_runner/variables.tf
> +  default     = "identity-rg"
@diegolagospagopa I'm gonna to remove it, however in the past days, I and @pasqualedevita thought that this name could be used by all teams in all subscriptions to host managed identities - but we haven't take any decision until now. What do you all think?

2023-10-04 15:48 UTC, pasqualedevita commented on identity_github_runner/variables.tf
> +  ]
this is a little bit dangerous: using copy/paste strategy will risk to give all these permissions to entire subscription, while we need to restrict this assignment to ona resource group or resource

2023-10-04 15:54 UTC, pasqualedevita commented on identity_github_runner/tests/main.tf
> +}
@diegolagospagopa main.tf is the same for all tests in this repo, we don't need to change it

2023-10-04 15:55 UTC, pasqualedevita commented on identity_github_runner/README.md
> +# GitHub Federatewd Identity for Runners
```suggestion
# GitHub Federatewd Identity for Azure
```
the module is generic for Azure or specific for GitHub runners?

2023-10-04 16:00 UTC, pasqualedevita commented on identity_github_runner/tests/resources.tf
> +resource "azurerm_resource_group" "rg" {
other tests folder in this repo has the readme.md where is specified what you need to change (basically only resources.tf file)

@Krusty93 also add the terraform.sh file

https://github.com/pagopa/terraform-azurerm-v3/blob/main/storage_account/tests/README.md

2023-10-04 16:01 UTC, pasqualedevita requested changes

2023-10-04 16:01 UTC, pasqualedevita commented on identity_github_runner/tests/resources.tf
> +    repository = "io-infra"
add variable :)

2023-10-04 16:07 UTC, pasqualedevita commented on identity_github_runner/variables.tf
> +variable "project" {
in other modules we use a generic name variable, 99% the caller repo use pattern: name=var.project+"my-resource", so I suggest to use `name` as variable

2023-10-04 16:10 UTC, pasqualedevita approved these changes

2023-10-04 16:10 UTC, pasqualedevita commented on identity_github_runner/variables.tf
> +  default     = "identity-rg"
Correct there isn't a standard right now but can introduce it. I'd like that all identities will be created in a `identity-rg` group. Maybe we can use add the convention "var.prefix-var.env-identity-rg"

2023-10-05 16:25 UTC, Krusty93 commented on identity_github_runner/variables.tf
> +variable "project" {
I've introduced `locals` to reuse the same construct for both resource group and identities. However, it requires two variables (prefix and env). See other comments

2023-10-05 16:26 UTC, Krusty93 commented on identity_github_runner/variables.tf
> +  default     = "identity-rg"
See other comments

2023-10-05 16:36 UTC, Krusty93 commented on identity_github_runner/locals.tf
> +locals {
I'm aware this is a strong assumption, but the goal here is to maintain a naming consistency since the beginning and removing responsibilities on devs - especially in the next days when they will start a migration "losing time for devops things they don't care about" (hope you get the message).

If you agree on this change, I'd also define the resource group in this module instead of referencing it using `data` for two reasons:
- if we are forcing the name, we already know the name and some work on dev side can be eliminated; of course, they would need to provide `location` as input variable
- if rg definition was outside of the module, devs needed to "guess" how the module internally forces rg name (ok there's `README.md` but it is not enough in my opinion)

For devs, providing `prefix` and `env_short` is really easy and convenient.

Anyway, let's talk about this. It's just a proposal

cc @diegolagospagopa @pasqualedevita @gunzip

2023-10-10 13:19 UTC, gunzip commented on identity_github_runner/tests/resources.tf
> +resource "azurerm_resource_group" "rg" {
I'd add comments inside the sources to clarify.

2023-10-11 15:56 UTC, Krusty93 commented on identity_github_runner/variables.tf
> +  ]
My proposal:
Subscription wide roles (module encapsulated):
- CI
  - `Reader`
  - `Reader and Data Access`
- CD
  - `Contributor`

Others permissions must be explicitly indicated by module consumer.

Downside of this approach: it takes time to understand all the necessary permissions for existing pipelines

2023-10-13 16:12 UTC, gunzip commented
consider that infrastructure (hcl) files will go into the code repository when using a monorepo.
does this works with monorepos that contain multiple projects and needs different environments?

2023-10-16 08:41 UTC, Krusty93 commented on identity_github_runner/variables.tf
> +  ]
Agreed with @pasqualedevita:
- CI: reader
- CD: contributor

Set as variables default

2023-10-16 17:17 UTC, Krusty93 commented
> consider that infrastructure (hcl) files will go into the code repository when using a monorepo. does this works with monorepos that contain multiple projects and needs different environments?
> 
> @lucacavallaro is this your concern?

Today I got in touch with @lucacavallaro and with the last commit, it does.

I've added some documentation for naming and resource management in `README.md` file

2023-10-31 14:24 UTC, diegolagospagopa approved these changes

2023-10-31 14:27 UTC, merged