Feat: Dns forwarder with load balancer and virtual machine scale set
pagopa/terraform-azurerm-v3 pull request #225
Opened 2024-01-25 12:01 UTC by umbcoppolabottazzi

### List of changes

Added a new module for the DNS forwarder that includes:

- Virtual Machine Scale Set with a custom image
- Load Balancer with a static IP
- Key Vault for storing the password of the Virtual Machine Scale Set
- Network Security Group for the Virtual Machine Scale Set
- [Optional]: Subnet for the Virtual Machine Scale Set + Subnet for the Load Balancer

### Motivation and context

### Type of changes

- [x] Add new module
- [ ] Update existing module
- [ ] Remove existing module

### Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### Other information

### Run checks

Useful commands to run checks on local machine

```sh
bash .utils/terraform_run_all.sh init local
pre-commit run -a
```

2024-01-25 13:15 UTC, mamari90 approved these changes

2024-01-25 13:33 UTC, diegolagospagopa commented on dns_forwarder_lb_vmss/main.tf
> +  count = var.subnet_vmss_id != null ? 0 : 1
Is correct that is not created is the subnet is external?, May be i created the subnet but i don't know anything about the NSG

2024-01-25 13:34 UTC, diegolagospagopa commented on dns_forwarder_lb_vmss/main.tf
> +module "lb" {
Please can you change the name in


```suggestion
module "load_balancer" {
```

2024-01-25 13:47 UTC, diegolagospagopa commented on dns_forwarder_lb_vmss/main.tf
> +  name         = local.prefix
Please give a more complex name to be more readable

2024-01-25 13:48 UTC, diegolagospagopa commented on dns_forwarder_lb_vmss/variables.tf
> +  default     = "StandardSSD_LRS"
Please change into


```suggestion
  default     = "StandardSSD_ZRS"
```

2024-01-25 13:49 UTC, diegolagospagopa requested changes
.

2024-01-29 13:51 UTC, diegolagospagopa approved these changes
.

2024-01-29 14:02 UTC, merged