fix: Supported connection between a certificate KV & CDN
pagopa/terraform-azurerm-v3 pull request #278
Opened 2024-04-09 18:10 UTC by umbcoppolabottazzi

### List of changes

With this PR, the association between the certificate stored on KV and the CDN is supported in cases where the hostname does not match the APEX domain

### Motivation and context

### Type of changes

- [ ] Add new module
- [x] Update existing module
- [ ] Remove existing module

### Does this introduce a breaking change?

- [ ] Yes
- [x] No

### Other information

### Run checks

Useful commands to run checks on local machine

```sh
bash .utils/terraform_run_all.sh init local
pre-commit run -a
```

2024-04-09 20:38 UTC, diegolagospagopa requested changes

2024-04-09 20:38 UTC, diegolagospagopa commented on cdn/variables.tf
> +variable "custom_hostname_kv" {
Please change into

```suggestion
variable "custom_hostname_kv_enabled" {
```

2024-04-09 20:38 UTC, diegolagospagopa commented on cdn/variables.tf
> +variable "enable_resource_advanced_threat_protection" {
```suggestion
variable "resource_advanced_threat_protection_enabled" {
```

2024-04-09 20:38 UTC, diegolagospagopa commented on cdn/variables.tf
> +  description = "Specific location for CDN"
Please put some examples

2024-04-09 20:38 UTC, diegolagospagopa commented on cdn/variables.tf
> +  default = null
If is mandatory, remove default

2024-04-10 09:02 UTC, umbcoppolabottazzi commented on cdn/variables.tf
> +  default = null
This variable is optional

2024-04-10 09:14 UTC, umbcoppolabottazzi commented on cdn/variables.tf
> +  description = "Specific location for CDN"
- Added a clearer description
- Added an example with a different location in the test folder

Thanks

2024-04-10 10:01 UTC, diegolagospagopa approved these changes

2024-04-10 10:01 UTC, merged