breaking: Devops 895 - azurerm_function_app_slot resource replacement
pagopa/terraform-azurerm-v3 pull request #73
Opened 2023-02-22 17:08 UTC by fmlisco

### List of changes

- Migration from the azurerm_function_app_slot resource to  the azurerm_linux_function_app_slot one
- the following variables have been removed since they are not used anymore:
os_type
linux_fx_version
resource_group_name
location
app_service_plan_id     

- the following variables have been renamed by the provider:
version ->functions_extension_version
function_app_name -> function_app_id

- the following variables have been added (they replace linux_fx_version):
*Please note you **only** need to set one of these variables (docker one aside)*
      dotnet_version              = var.dotnet_version
      use_dotnet_isolated_runtime = var.use_dotnet_isolated_runtime
      java_version                = var.java_version
      python_version              = var.python_version
      node_version                = var.node_version
      powershell_core_version     = var.powershell_core_version
      use_custom_runtime          = var.use_custom_runtime
      dynamic "docker" {
        for_each = length(var.docker) > 0 ? [1] : []
        content {
          registry_url      = var.docker.registry_url
          image_name        = var.docker.image_name
          image_tag         = var.docker.image_tag
          registry_username = var.docker.registry_username
          registry_password = var.docker.registry_password
        }
      }

### Motivation and context

Since the resource **azurerm_function_app_slot** has been deprecated in version 3.0 of the AzureRM provider, the newer **azurerm_linux_function_app_slot** resource is used in this module. 

### Type of changes

- [x] Resource replaced because of deprecation
- [ ] Update existing module
- [ ] Remove existing module

### Does this introduce a breaking change?

- [x] Yes
- [ ] No

### Other information

### Run checks

The Terraform templates saved in the folder **terraform-azurerm-v3/function_app_slot/tests** have been created to test this module.
- cd terraform-azurerm-v3/function_app_slot/tests/
- terraform init
- terraform plan
- terraform apply

2023-02-23 08:20 UTC, pasqualedevita requested changes

2023-02-23 08:20 UTC, pasqualedevita commented on function_app_slot/tests/main.tf
> +module "func_python_slot" {
probably here is missing the function_app_slot module

2023-02-23 08:20 UTC, pasqualedevita commented on function_app_slot/README.md
> +No migration is necessary.
I think that we can copy the function_app script

2023-02-23 08:20 UTC, pasqualedevita commented on function_app_slot/tests/versions.tf
> +      version = ">= 3.30.0, <= 3.43.0"
```suggestion
      version = ">= 3.30.0, <= 3.44.1"
```

2023-02-23 08:20 UTC, pasqualedevita commented on function_app_slot/main.tf
> -  os_type                    = var.os_type
add client_certificate_enabled as in https://github.com/pagopa/terraform-azurerm-v3/blob/main/function_app/main.tf#L239

2023-02-23 09:13 UTC, fmlisco commented on function_app_slot/main.tf
> -  os_type                    = var.os_type
done

2023-02-23 13:47 UTC, fmlisco commented on function_app_slot/tests/main.tf
> +module "func_python_slot" {
fixed

2023-02-23 13:48 UTC, fmlisco commented on function_app_slot/README.md
> +No migration is necessary.
fixed

2023-02-24 11:02 UTC, pasqualedevita approved these changes

2023-02-24 11:02 UTC, merged